export const CHICKEN_BREEDS = [
  'Rhode Island Red',
  'White Leghorn',
  'Plymouth Rock (Barred)',
  'Australorp',
  'ISA Brown',
  'Sussex (Light or Speckled)',
  'Wyandotte',
  'Red Sex Link',
  'Golden Comet',
  'Hy-Line Brown',
  'Lohmann Brown',
  'Ameraucana',
  'Easter Egger',
  'Marans',
  'Hamburg',
  'Ancona',
  'Campine',
  'Fayoumi',
  'Welsummer',
  'Dominique',
  'Orpington',
  'Delaware',
  'California White',
  'Andalusian',
  'Minorca',
  'Silver Spangled Hamburg',
  'Bovan Brown',
  'Cinnamon Queen',
  'Austral White',
  'ISA Warren',
  'Other',
];

export const DUCK_BREEDS = [
  'Khaki Campbell',
  'Indian Runner',
  'Welsh Harlequin',
  'Golden 300 Hybrid',
  'White Layer',
  'Buff Orpington',
  'Magpie',
  'Ancona',
  'Silver Appleyard',
  'Saxony',
  'Golden Cascade',
  'Pekin (White Pekin)',
  'Buff',
  'Fawn and White Runner',
  'Campbell (Original)',
  'Blue Swedish',
  'Cayuga',
  'Rouen',
  'Crested',
  'Abacot Ranger',
  'Bali',
  'Hook Bill',
  'Black East Indies',
  'Australian Spotted',
  'Shetland',
  'Other',
];

export const RABBIT_BREEDS = [
  'American',
  'Californian',
  'Dutch',
  'English Angora',
  'Flemish Giant',
  'Holland Lop',
  'Lionhead',
  'Mini Lop',
  'New Zealand White',
  'Rex',
  'Other',
];
