export const CHICKEN_BREEDS = [
  'Rhode Island Red',
  'Leghorn',
  'Plymouth Rock',
  'Sussex',
  'Orpington',
  'Wyandotte',
  'Australorp',
  'Marans',
  'Brahma',
  'Silkie',
  'Cochin',
  'Polish',
  'Frizzle',
  'Ameraucana',
  'Easter Egger',
  'Buff Orpington',
  'Barred Rock',
  'Speckled Sussex',
  'Rhode Island White',
  'New Hampshire Red',
  'Delaware',
  'Jersey Giant',
  'Langshan',
  'Minorca',
  'Ancona',
  'Andalusian',
  'Campine',
  'Catalana',
  'Crèvecoeur',
  'Dorking',
  'Hamburg',
  'Lakenvelder',
  'Old English Game',
  'Redcap',
  'Sebright',
  'Sumatra',
  'Welsummer',
  'Other',
];

export const RABBIT_BREEDS = [
  'New Zealand White',
  'Californian',
  'Flemish Giant',
  'Rex',
  'Holland Lop',
  'Mini Lop',
  'Lionhead',
  'Dutch',
  'English Angora',
  'American',
  'Other',
];
