export const CHICKEN_BREEDS = [
  'Rhode Island Red',
  'White Leghorn',
  'Plymouth Rock (Barred)',
  'Australorp',
  'ISA Brown',
  'Sussex (Light or Speckled)',
  'Wyandotte',
  'Red Sex Link',
  'Golden Comet',
  'Hy-Line Brown',
  'Lohmann Brown',
  'Ameraucana',
  'Easter Egger',
  'Marans',
  'Hamburg',
  'Ancona',
  'Campine',
  'Fayoumi',
  'Welsummer',
  'Dominique',
  'Orpington',
  'Delaware',
  'California White',
  'Andalusian',
  'Minorca',
  'Silver Spangled Hamburg',
  'Bovan Brown',
  'Cinnamon Queen',
  'Austral White',
  'ISA Warren',
  'Other',
];

export const RABBIT_BREEDS = [
  'American',
  'Californian',
  'Dutch',
  'English Angora',
  'Flemish Giant',
  'Holland Lop',
  'Lionhead',
  'Mini Lop',
  'New Zealand White',
  'Rex',
  'Other',
];
